server:
  port: 8003
spring:
  application:
    name: @pom.artifactId@
  main:
    ## 允许定义同名的FeignClient,name
    allow-bean-definition-overriding: true
  zipkin:
#    base-url: localhost:9411
    sender:
      type: RABBIT
  rabbitmq:
    addresses: 0.0.0.0:5672
    username: guest
    password: guest
  sleuth:
    sampler:
      # 设置抽样比例
      probability: 1.0
  datasource:
    url: jdbc:postgresql://localhost:5432/gkcloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath:**/*.xml
  type-aliases-package: com.gknoone.cloud.plus.model
  type-handlers-package: com.gknoone.cloud.plus.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    call-setters-on-nulls: true
eureka:
  client:
    service-url:
      defaultZone: http://gknoone:gk123456@peer1:8111/eureka/,http://gknoone:gk123456@peer2:8112/eureka/
    healthcheck:
      # 开启健康检查
      enabled: true
  instance:
    # 将自己的IP注册到eureka上，若为false，则注册微服务所在操作系统的hostname到eureka上
    prefer-ip-address: true
    # 实例id，配置前192.168.13.111:provider-user:8002，配置后provider-user:192.168.13.111:8002
    # 默认${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id}:${service.port}
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
    # 自定义实例跳转链接
    status-page-url: https://github.com/gknoone
    # 发送心跳给server端的频率 （开发环境开启，默认30秒）
    lease-renewal-interval-in-seconds: 5
    # server至上一次收到心跳之后，等待下一次心跳的超时时间，超时未收到心跳，移除instance （开发环境开启，默认90秒）
    lease-expiration-duration-in-seconds: 5

logging:
  level:
    # 配合FeignClient的Configuration自定义的Logger.LEVEL使用
    com.gknoone.cloud.plus.provider.service: DEBUG
  # 配置Admin的日志文件输出位置
  file: /Users/baweibin/Downloads/gknoone-cloud-plus/log/provider/provider-test.log

# 开启监控点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: ALWAYS

feign:
  hystrix:
    # 开启熔断
    enabled: true