spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gkcloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: gknoone
      password: gk123456
mybatis:
  mapper-locations: classpath:**/*.xml
  type-aliases-package: com.gknoone.cloud.plus.common.core.model
  type-handlers-package: com.gknoone.cloud.plus.common.core.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    call-setters-on-nulls: true