spring:
  zipkin:
    # base-url: http://localhost:9411
    sender: 
      type: RABBIT
  rabbitmq:
    addresses: amqp://localhost:5672
    username: guest
    password: guest
  sleuth:
    sampler:
      # 设置抽样比例
      probability: 1.0
logging:
  level:
    root: INFO
    # 开启sleuth的debug日志
    org.springframework.cloud.sleuth: DEBUG