spring:
  main:
    ## 允许定义同名的FeignClient,name
    allow-bean-definition-overriding: true
feign:
  hystrix:
    # 开启熔断
    enabled: true
logging:
  level:
    # 配合FeignClient的Configuration自定义的Logger.LEVEL使用
    com.uyaki.cloud.provider.service: DEBUG