server:
  port: 8333
spring:
  application:
    name: @pom.artifactId@
  boot:
    admin:
      ui:
        # 自定义显示title
        title: gknoone-cloud-plus-Admin-Server
  # 配置认证信息，client端需要对应配置（ 如果配置到了eureka，则不需要）
  # spring.boot.admin.client.url=http://localhost:8333
  # spring.boot.admin.client.username=gknoone
  # spring.boot.admin.client.password=gk123456
  security:
    user:
      name: gknoone
      password: gk123456